### ISSUE TITLE
Customize Shortcut

### ISSUE THREAD

**Issue by YayC** [castus/xcode-duplicate-line#1]
Great plugin, I was really missing this feature from other editors!

Is there a way to customize the shortcut? I'm used to command + shift + D instead.

**Comment by nicoschuele** [comment]
I could set CMD+SHIFT+D with...
1. Go to System Preferences
2. Keyboard
3. Shortcuts
4. App Shortcuts
5. +
6. Application: Xcode
7. Menu Title: Duplicate Line
8. Keyboard Shortcut: <type your desired shortcut>
9. Add

Voilà ;-)

**Comment by YayC** [comment]
That did it, thanks! Maybe this should be added to the readme.

**Comment by nicoschuele** [comment]
It's more a global OS X thing. I usually override shortcuts in Mail, Safari, etc using this.

**Comment by YayC** [comment]
Yup, might be good as a reminder for other osx users though

**Comment by castus** [comment]
Sorry for late response. I've used ^⇧D because it was free, Xcode no used it ;) Thanks guys for pointing that out that this could be changed. I'll definitely add it to readme.
